- name: Ensure ssh port is open
  vars:
    ansible_connection: local
  wait_for:
    port: 22
    delay: 10
    search_regex: OpenSSH
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'