- name: Install python3 and haproxy
  vars:
    ansible_python_interpreter: /usr/bin/python
  yum:
    name:
      - python3
      - haproxy
    update_cache: true
    state: present
- name: Copy the config file to haproxy server
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Restart haproxy service
  systemd:
    name: haproxy
    state: restarted