- name: Install python3 and apache
  vars:
    ansible_python_interpreter: /usr/bin/python
  yum:
    name: 
      - python3
      - httpd
      - libselinux-python3
    update_cache: true
    state: present

- name: Create www directory
  file:
    path: /opt/html
    state: directory

- name: Create start page
  template:
    src: index.html
    dest: /opt/html/index.html

- name: Change main configuration file
  template:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf

- name: Start apache server
  service:
    name: httpd
    state: started